services:
  postgresdb:
    image: postgres:18.0
    environment:
      POSTGRES_PASSWORD: swen1db
      POSTGRES_USER: swen1user
      POSTGRES_DB: tododb
    ports:
      - 5432:5432
    volumes:
      - swen1v:/var/lib/postgresql

volumes:
  swen1v:
